CREATE SEQUENCE CARTNO_SEQ
    MAXVALUE 9999999
    NOCACHE;

SELECT * FROM CART C, PRODUCTENROLL PE WHERE MEMBERID = 'nutellajang';
--장바구니에 물건 추가
INSERT INTO CART (CARTNO, MEMBERID, PRODUCTEA, PRODUCTCODE, CARTPRICE)
            VALUES(CARTNO_SEQ.NEXTVAL, 'nutellajang', 2, 11, 60000);

--장바구니 가져오기
SELECT * FROM CART C, PRODUCTENROLL E, PRODUCT P WHERE C.PRODUCTCODE = P.PRODUCTCODE AND E.PRODUCTCODE = P.PRODUCTCODE AND MEMBERID = 'nutellajang';

--장바구니 삭제
DELETE FROM CART WHERE CARTNO = 2;

--장바구니 갯수 변경
UPDATE CART SET PRODUCTEA = 5 WHERE CARTNO = 44;
SELECT * FROM CART C, PRODUCTENROLL E, PRODUCT P WHERE C.PRODUCTCODE = P.PRODUCTCODE AND E.PRODUCTCODE = P.PRODUCTCODE AND CARTNO = 47;
commit;

--장바구니 중복
SELECT COUNT(*) FROM CART C, PRODUCTENROLL PE WHERE MEMBERID = 'nutellajang' AND PECODE = 1;