SELECT * FROM MEMBER;
COMMIT;
--SIGNUP
INSERT INTO MEMBER ( MEMBERID, MEMBERPW, MEMBERNAME, MEMBERTEL, MEMBEREMAIL, MEMBERADDRESS,
                     MEMBERPOST, MEMBERBIRTH, GRADELEVEL)
            VALUES(  'MEMBER2', '1234', 'STELLA', '010-1212-1211', 'STELLAJANG@naver.com', '스텔라네집',
                     '110-111', TO_DATE('1991-10-21', 'YY-MM-DD'), 1);
--가입 ID 체크
SELECT MEMBERID FROM MEMBER WHERE MEMBERID = 'nutellajang';

-- SESSION에 저장할 정보
SELECT * FROM MEMBER M, MEMBERGRADE MG WHERE MEMBERID = 'MEMBER2' AND M.GRADELEVEL = MG.GRADELEVEL;
-- 로그인
SELECT * FROM MEMBER WHERE MEMBERID = 'MEMBER2' AND MEMBERPW='1234' AND MEMBERSTATUS = 1;
--아이디 삭제 (사용자)
UPDATE MEMBER SET MEMBERSTATUS = 0 WHERE MEMBERID='MEMBER1';
-- 맴버 리스트
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM MEMBER) A)
    WHERE RN BETWEEN 1 AND 3 AND MEMBERSTATUS > 0;
--맴버 숫자
SELECT COUNT(*) FROM MEMBER WHERE MEMBERSTATUS > 0;

SELECT * FROM MEMBER WHERE MEMBERID = 'MEMBER2' AND MEMBERPW= '1234' AND MEMBERSTATUS = 1;
-- 정보수정
UPDATE MEMBER SET MEMBERNAME = '스텔라장', MEMBERTEL='010-2020-1010', MEMBERPW='jang' WHERE MEMBERID ='nutellajang';
commit;
UPDATE MEMBER SET TOTALSPENT = 100001 WHERE MEMBERID ='nutellajang';
SELECT * FROM MEMBER M, MEMBERGRADE MG WHERE TOTALSPENT BETWEEN LOWSPENT AND HISPENT;
COMMIT;
--탈퇴회원 검색
SELECT * FROM MEMBER WHERE MEMBERSTATUS = 0;