SELECT * FROM NOTICE ORDER BY NOTICEEVENT DESC, NOTICENO DESC;
CREATE SEQUENCE NOTICENO_SEQ
        MAXVALUE 99999
        NOCACHE
        NOCYCLE;
--글쓰기
INSERT INTO NOTICE (NOTICENO, NOTICENAME, NOTICECONTENT, NOTICEEVENT, ADMINID)
            VALUES (NOTICENO_SEQ.NEXTVAL, '테스트용 공지사항입니다.', '테스트용 공지사항입니다.', 0, 'ADMIN');
--공지사항 수정
UPDATE NOTICE 
    SET NOTICENAME = '수정됨', NOTICECONTENT = '수정됨', NOTICEEVENT = 1, ADMINID='ADMIN' 
    WHERE NOTICENO = 1;
--리스트조회
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM NOTICE ORDER BY NOTICEEVENT DESC, NOTICENO DESC) A)
    WHERE RN BETWEEN 1 AND 10 AND NOTICEEVENT > -1;
--글삭제
UPDATE NOTICE SET NOTICEEVENT = -1 WHERE NOTICENO = 8;
commit;
--글 조회
SELECT * FROM NOTICE WHERE NOTICENO = 1;

-- 공지사항 가져오기
SELECT * FROM (SELECT ROWNUM RN, N.* FROM (SELECT * FROM NOTICE where noticeevent != 1 ORDER BY NOTICENO DESC) N )  WHERE rn = 2 ;