CREATE SEQUENCE ODNO_SEQ
    MAXVALUE 999999
    NOCACHE;
CREATE SEQUENCE ORDERNO_SEQ
    MAXVALUE 999999
    NOCACHE;


SELECT * FROM ORDERS;

SELECT * FROM ORDERDETAIL;
SELECT TO_CHAR(SYSDATE,'YY-MM-DD HH:MI:SS') FROM DUAL;
-- 주문 생성
INSERT INTO ORDERS (ORDERNO, ORDERADDRESS, ORDERTEL, ORDERTOTAL, MEMBERID)
            VALUES (ORDERNO_SEQ.NEXTVAL, '서울시 종로구 육의전빌딩 8층', '010-2020-1111', 30000, 'nutellajang');
-- 주문 상세
INSERT INTO ORDERDETAIL (ODNO, PRODUCTCODE, ORDERNO, ODPRICE, ODCNT)
                VALUES  (ODNO_SEQ.NEXTVAL, 1, 2, 30000, 1);

--주문 상세 보기
SELECT * FROM ORDERDETAIL OD, ORDERS O, MEMBER M WHERE OD.ORDERNO = O.ORDERNO AND M.MEMBERID = O.MEMBERID;
commit;
--ORDERSTATUS 1 == 주문중 2 == 주문완료 3==배송처리중 4 ==배송처리완료
SELECT ORDERNO FROM ORDERS WHERE MEMBERID = 'nutellajang' and orderstatus = 1;