SELECT * FROM PRODUCTENROLL;
CREATE SEQUENCE PECODE_SEQ
    MAXVALUE 9999999
    NOCACHE
    NOCYCLE;
    

--상품 갯수
SELECT COUNT(*) FROM PRODUCTENROLL WHERE PESTATUS > 0;

--상품 등록
INSERT INTO PRODUCTENROLL (PECODE, PRODUCTCODE, PENAME, PECONTENT, PEIMG1, PEIMG2, PEPRICE, PEPOINT, PEDISCOUNT, PESTARS)
                VALUES    (PECODE_SEQ.nextval, 15, '오설록 120g', '세부내용', 'IMG1', 'IMG2', 12000, 50, 0, 0); 
--상품 리스트
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM PRODUCTENROLL ORDER BY PERDATE) A) E, PRODUCT P 
    WHERE RN BETWEEN 1 AND 3 AND E.PRODUCTCODE = P.PRODUCTCODE;
COMMIT;

SELECT * FROM PRODUCT P, PRODUCTENROLL E WHERE P.PRODUCTCODE = E.PRODUCTCODE;
SELECT PRODUCTNAME FROM PRODUCT;
SELECT * FROM PRODUCT P, product_type T, product_brand B 
WHERE PRODUCTNAME = '오설록 녹차' AND T.PTYPECODE = P.PTYPECODE AND B.PBRANDCODE = P.PBRANDCODE;

-- 상품 상세보기
SELECT * FROM PRODUCTENROLL E, PRODUCT P WHERE PECODE = 6 AND P.PRODUCTCODE = E.PRODUCTCODE;
SELECT * FROM PRODUCT P, product_type T, product_brand B
				WHERE PRODUCTNAME = "" AND T.PTYPECODE = P.PTYPECODE AND B.PBRANDCODE = P.PBRANDCODE;
                
SELECT * FROM PRODUCTENROLL WHERE PENAME LIKE '%A%';