SELECT * FROM QNABOARD;

--갯수세기
SELECT COUNT(*) FROM QNABOARD;

-- 글 작성 1이면 유저 2는 관리자 0은 삭제
INSERT INTO QNABOARD (QNANO, MEMBERID, QNANAME, QNACONTENT, QNAANSWER, QNAGROUP)
            VALUES(QNANO_SEQ.NEXTVAL, 'nutellajang', '테스트 글입니다.', '어렵습니다.',1, QNANO_SEQ.NEXTVAL);

--글 목록 가져오기
SELECT * FROM (SELECT ROWNUM RN, A.* 
    FROM (SELECT * FROM QNABOARD WHERE QNAANSWER > 0 ORDER BY QNAGROUP DESC, QNAANSWER) A) 
    WHERE RN BETWEEN 1 AND 3;
    
COMMIT;
--글 가져오기
SELECT * FROM QNABOARD WHERE QNANO = 1;